# Build the testserver binary
# Docker command must be invoked from the projec root directory
FROM golang:1.25@sha256:6ca9eb0b32a4bd4e8c98a4a2edf2d7c96f3ea6db6eb4fc254eef6c067cf73bb4 AS builder

ARG TARGETARCH

ENV GOARCH=$TARGETARCH
ENV CGO_ENABLED=1

WORKDIR /src

# Copy the go manifests and source
COPY internal/test/ internal/test/
COPY go.mod go.mod
COPY go.sum go.sum

# Build/link statically with CGO, external static linking
RUN go build -tags -a -ldflags '-linkmode external -extldflags "-static"' -o testserver ./internal/test/integration/components/testserver/testserver.go

# Create final image from minimal + built binary
#TODO: use minimal image
FROM debian:12@sha256:6337ad82d5c764a8b6a16cde86b157fdce353e36d8ca06fc1b16d4f34d29960e

WORKDIR /
RUN mkdir -p x509
COPY --from=builder /src/internal/test/integration/components/testserver/x509/server_test_cert.pem x509
COPY --from=builder /src/internal/test/integration/components/testserver/x509/server_test_key.pem x509
COPY --from=builder /src/testserver .
USER 0:0

CMD [ "/testserver" ]
